version: "3.8"

services:
  backend:
    # build: ./backend
    image: ${BACKEND_IMAGE:-localhost/daily-git-brief-backend:latest}
    container_name: daily-git-brief-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    # build: ./frontend
    image: ${FRONTEND_IMAGE:-localhost/daily-git-brief-frontend:latest}
    container_name: daily-git-brief-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  data:
